services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    env_file:
      - rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge