services:
  rabbitmq1:
    image: rabbitmq:4.0-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=mirzaq
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster-network

  rabbitmq2:
    image: rabbitmq:4.0-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    container_name: rabbitmq2
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster-network

  rabbitmq3:
    image: rabbitmq:4.0-management
    hostname: rabbitmq3
    depends_on: 
      - rabbitmq1
    container_name: rabbitmq3
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster-network

  haproxy:
    image: haproxy:1.7
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    networks:
      - rabbitmq-cluster-network

networks:
  rabbitmq-cluster-network:
    driver: bridge